# Generated by Django 2.0.7 on 2018-08-07 14:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180803_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
    ]
